# fly.toml app configuration file generated for ribbot on 2024-04-04T22:34:46-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ribbot'
primary_region = 'yyz'

[build]

[processes]
  app = 'run -A ./src/main.ts'

[http_service]
  http_checks = []
  tcp_checks = []
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
